services:
  app:
    build: .
    ports:
      - "8080:8080"
      - "9000:9000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM}
    volumes:
      - .:/app

  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    command: >
      bash -c "
        echo 'CREATE DATABASE test_db;' > /docker-entrypoint-initdb.d/init.sql &&
        docker-entrypoint.sh postgres
      "

  grpc:
    build: .
    command: python app/server_grpc.py
    working_dir: /app
    environment:
      - PYTHONPATH=/app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - db



volumes:
  postgres_data: