# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from grpc import pvz_pb2 as grpc_dot_pvz__pb2


class PVZServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetPVZList = channel.unary_unary(
                '/app.grpc.PVZService/GetPVZList',
                request_serializer=grpc_dot_pvz__pb2.GetPVZListRequest.SerializeToString,
                response_deserializer=grpc_dot_pvz__pb2.GetPVZListResponse.FromString,
                )


class PVZServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetPVZList(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PVZServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetPVZList': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPVZList,
                    request_deserializer=grpc_dot_pvz__pb2.GetPVZListRequest.FromString,
                    response_serializer=grpc_dot_pvz__pb2.GetPVZListResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'app.grpc.PVZService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class PVZService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetPVZList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/app.grpc.PVZService/GetPVZList',
            grpc_dot_pvz__pb2.GetPVZListRequest.SerializeToString,
            grpc_dot_pvz__pb2.GetPVZListResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
