# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpc/pvz.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0egrpc/pvz.proto\x12\x08\x61pp.grpc\x1a\x1fgoogle/protobuf/timestamp.proto\"V\n\x03PVZ\x12\n\n\x02id\x18\x01 \x01(\t\x12\x35\n\x11registration_date\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x0c\n\x04\x63ity\x18\x03 \x01(\t\"\x13\n\x11GetPVZListRequest\"1\n\x12GetPVZListResponse\x12\x1b\n\x04pvzs\x18\x01 \x03(\x0b\x32\r.app.grpc.PVZ2U\n\nPVZService\x12G\n\nGetPVZList\x12\x1b.app.grpc.GetPVZListRequest\x1a\x1c.app.grpc.GetPVZListResponseB*Z(github.com/yourproject/pvz/pvz_v1;pvz_v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'grpc.pvz_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z(github.com/yourproject/pvz/pvz_v1;pvz_v1'
  _globals['_PVZ']._serialized_start=61
  _globals['_PVZ']._serialized_end=147
  _globals['_GETPVZLISTREQUEST']._serialized_start=149
  _globals['_GETPVZLISTREQUEST']._serialized_end=168
  _globals['_GETPVZLISTRESPONSE']._serialized_start=170
  _globals['_GETPVZLISTRESPONSE']._serialized_end=219
  _globals['_PVZSERVICE']._serialized_start=221
  _globals['_PVZSERVICE']._serialized_end=306
# @@protoc_insertion_point(module_scope)
