# generated by datamodel-codegen:
#   filename:  swagger.yaml
#   timestamp: 2025-04-20T19:32:25+00:00

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Optional
from uuid import UUID

from pydantic import BaseModel, EmailStr


class Token(BaseModel):
    __root__: str


class Role(Enum):
    employee = 'employee'
    moderator = 'moderator'


class User(BaseModel):
    id: Optional[UUID] = None
    email: EmailStr
    role: Role


class City(Enum):
    Москв�_ = 'Москва'
    С�_нк�__Пе�_ер�_ург = 'Санкт-Петербург'
    К�_�_�_нь = 'Казань'


class PVZ(BaseModel):
    id: Optional[UUID] = None
    registrationDate: Optional[datetime] = None
    city: City


class Status(Enum):
    in_progress = 'in_progress'
    close = 'close'


class Reception(BaseModel):
    id: Optional[UUID] = None
    dateTime: datetime
    pvzId: UUID
    status: Status


class Type(Enum):
    э�_ек�_роник�_ = 'электроника'
    оде�_д�_ = 'одежда'
    о�_увь = 'обувь'


class Product(BaseModel):
    id: Optional[UUID] = None
    dateTime: Optional[datetime] = None
    type: Type
    receptionId: UUID


class Error(BaseModel):
    message: str
